### ISSUE TITLE
启用会话隔离后无法在左侧生成聊天记录，今天更新之后的版本

### ISSUE THREAD

**Issue by lyy0709** [maidou2023/chatgpt-mirror-docker#11]
启用会话隔离后无法在左侧生成聊天记录
日志如下
![图片](https://github.com/maidou2023/chatgpt-mirror-docker/assets/65712338/f58f3051-f37b-4a5b-8f1b-5cf87b64cb40)

**Comment by liuhuapiaoyuan** [comment]
对，正在修复中

**Comment by lyy0709** [comment]
期待佬的修复

**Comment by liuhuapiaoyuan** [comment]
新版本已经更新

**Comment by lyy0709** [comment]
谢谢大佬

**Comment by lyy0709** [comment]
我测试了一下依旧无法隔离生成，不隔离生成是正常的
![图片](https://github.com/maidou2023/chatgpt-mirror-docker/assets/65712338/4bd8d8e9-517d-4746-a552-122de89c4215)

**Comment by maidou2023** [comment]
不应该啊，我这边测试都是正常的，你可以给我一个账号我看看问题

**Comment by lyy0709** [comment]
网站：gpt.cuproxy.top
usertoken登录：test1

**Comment by liuhuapiaoyuan** [comment]
我看过了，你这个应该是版本没更新过来，按道理gpts的页面报错也修复了。
![1713279289705](https://github.com/maidou2023/chatgpt-mirror-docker/assets/8020726/0277fffa-a549-4901-a312-3dbee968f22c)

**Comment by lyy0709** [comment]
好的我再拉一遍更新

**Comment by liuhuapiaoyuan** [comment]
后台有啥异常吗？

**Comment by lyy0709** [comment]
没有明显异常，看日志也没报错，只要不开隔离生成标题怎么的都是正常的

**Comment by liuhuapiaoyuan** [comment]
> 没有明显异常，看日志也没报错，只要不开隔离生成标题怎么的都是正常的 gpts商店还是错误

访问下gpts 看下日志

**Comment by liuhuapiaoyuan** [comment]
> 没有明显异常，看日志也没报错，只要不开隔离生成标题怎么的都是正常的 gpts商店还是错误

访问下gpts 看下日志

**Comment by lyy0709** [comment]
![图片](https://github.com/maidou2023/chatgpt-mirror-docker/assets/65712338/36e8f409-2b4d-4144-98a5-c17300aa1c06)
访问gpts的日志

**Comment by liuhuapiaoyuan** [comment]
你网关是怎么做的？

**Comment by liuhuapiaoyuan** [comment]
> ![图片](https://private-user-images.githubusercontent.com/65712338/322909914-36e8f409-2b4d-4144-98a5-c17300aa1c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODIzNzIsIm5iZiI6MTcxMzI4MjA3MiwicGF0aCI6Ii82NTcxMjMzOC8zMjI5MDk5MTQtMzZlOGY0MDktMmI0ZC00MTQ0LTk4YTUtYzE3MzAwYWExYzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YTNhZDhlNjcyZTlkNTk3M2ZlMjM4MDQzNWM4MTAyMjIyYjk1ZmYyOGE5MWIzZjE4NTk3YzMwMGZlMDZlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vk--3xdt1WMowOofJqZ3gPfMsMS-YI8nRUtG26kS45s) 访问gpts的日志

加我微信 就这个账号
