### ISSUE TITLE
没有GPT4和GPTs

### ISSUE THREAD

**Issue by XksA-me** [maidou2023/chatgpt-mirror-docker#6]
![image](https://github.com/maidou2023/chatgpt-mirror-docker/assets/43670614/d26200d1-452a-4142-b63f-21c44f731a7f)
你好，我部署登录后没有出现 GPT4和GPTs，配置的 gpt4 帐号，有交流群吗或者相关配置教程

并且已经 docker compose pull 过了

**Comment by liuhuapiaoyuan** [comment]
网关配置了吗？

**Comment by XksA-me** [comment]
你好，我使用的 clash，在 yml 文件设置了
```
# 接入网关地址 可以用cloudflare/clash之类的代理
CHATPROXY: "127.0.0.1:7890"
# 接入网关的授权码
AUTHKEY: ""
```

好像没有起效

**Comment by liuhuapiaoyuan** [comment]
clash 不行

**Comment by XksA-me** [comment]
谢谢，那如果要自己设置 就只能查 如何使用 cloudflare 进行网关设置是吗
